int led1 = 2;
int led2 = 3;
int led3 = 4;
int led4 = 5;
int led5 = 6;
int led6 = 7;
int led7 = 8;
int led8 = 9;
int led9 = 10;
int led10 = 11;
int tempo = 100;

void setup() {
  pinMode(led1,OUTPUT);
  pinMode(led2,OUTPUT);
  pinMode(led3,OUTPUT);
  pinMode(led4,OUTPUT);
  pinMode(led5,OUTPUT);
  pinMode(led6,OUTPUT);
  pinMode(led7,OUTPUT);
  pinMode(led8,OUTPUT);
  pinMode(led9,OUTPUT);
  pinMode(led10,OUTPUT);
}

void loop() {
  digitalWrite(led1,HIGH);
  delay(tempo);
  digitalWrite(led1,LOW);
  delay(tempo);
  digitalWrite(led2,HIGH);
  delay(tempo);
  digitalWrite(led2,LOW);
  delay(tempo);
  digitalWrite(led3,HIGH);
  delay(tempo);
  digitalWrite(led3,LOW);
  delay(tempo);
  digitalWrite(led4,HIGH);
  delay(tempo);
  digitalWrite(led4,LOW);
  delay(tempo);
  digitalWrite(led5,HIGH);
  delay(tempo);
  digitalWrite(led5,LOW);
  delay(tempo);
  digitalWrite(led6,HIGH);
  delay(tempo);
  digitalWrite(led6,LOW);
  delay(tempo);
  digitalWrite(led7,HIGH);
  delay(tempo);
  digitalWrite(led7,LOW);
  delay(tempo);
  digitalWrite(led8,HIGH);
  delay(tempo);
  digitalWrite(led8,LOW);
  delay(tempo);
  digitalWrite(led9, HIGH);
  delay(tempo);
  digitalWrite(led9,LOW);
  delay(tempo);
  digitalWrite(led10,HIGH);
  delay(tempo);
  digitalWrite(led10,LOW);
  delay(tempo);
  //Agora inicia o movimento ao contrario
  digitalWrite(led10,HIGH);
  delay(tempo);
  digitalWrite(led10,LOW);
  delay(tempo);
  digitalWrite(led9,HIGH);
  delay(tempo);
  digitalWrite(led9,LOW);
  delay(tempo);
  digitalWrite(led8,HIGH);
  delay(tempo);
  digitalWrite(led8,LOW);
  delay(tempo);
  digitalWrite(led7,HIGH);
  delay(tempo);
  digitalWrite(led7,LOW);
  delay(tempo);
  digitalWrite(led6,HIGH);
  delay(tempo);
  digitalWrite(led6,LOW);
  delay(tempo);
  digitalWrite(led5,HIGH);
  delay(tempo);
  digitalWrite(led5,LOW);
  delay(tempo);
  digitalWrite(led4,HIGH);
  delay(tempo);
  digitalWrite(led4,LOW);
  delay(tempo);
  digitalWrite(led3,HIGH);
  delay(tempo);
  digitalWrite(led3,LOW);
  delay(tempo);
  digitalWrite(led2,HIGH);
  delay(tempo);
  digitalWrite(led2,LOW);
  delay(tempo);
  digitalWrite(led1,HIGH);
  delay(tempo);
  digitalWrite(led1,LOW);
  delay(tempo);
}
